version: "3"
services:
    db:
        image: mysql:8.0.40-debian
        container_name: "mysql"
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=123
        ports:
            - 3306:3306
